/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2024-05-09 17:19:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/OneDrive%20-%20University%20of%20Technology%20and%20Education/petshop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/petshop-cats/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1714401051284L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1710262135216L));
    _jspx_dependants.put("jar:file:/D:/OneDrive%20-%20University%20of%20Technology%20and%20Education/petshop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/petshop-cats/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1710436164282L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Trang chủ</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   \r\n");
      out.write("        <!-- Carousel Start -->\r\n");
      out.write("        <div class=\"container-fluid carousel-header px-0\">\r\n");
      out.write("            <div id=\"carouselId\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("                <ol class=\"carousel-indicators\">\r\n");
      out.write("                    <li data-bs-target=\"#carouselId\" data-bs-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("                    <li data-bs-target=\"#carouselId\" data-bs-slide-to=\"1\"></li>\r\n");
      out.write("                    <li data-bs-target=\"#carouselId\" data-bs-slide-to=\"2\"></li>\r\n");
      out.write("                </ol>\r\n");
      out.write("                <div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("                    <div class=\"carousel-item active\">\r\n");
      out.write("                        <img src=\"template/web/img/carousel-1.jpg\" class=\"img-fluid\" alt=\"Image\">\r\n");
      out.write("                        <div class=\"carousel-caption\">\r\n");
      out.write("                            <div class=\"p-3\" style=\"max-width: 900px;\">\r\n");
      out.write("                                <h4 class=\"text-primary text-uppercase mb-3\">PET SHOP</h4>\r\n");
      out.write("                                <h1 class=\"display-1 text-capitalize text-dark mb-3\">Dịch vụ chăm sóc sức khỏe </h1>\r\n");
      out.write("                                <p class=\"mx-md-5 fs-4 px-4 mb-5 text-dark\">Đội ngũ bác sĩ thú y chuyên nghiệp của chúng tôi sẽ kiểm tra sức khỏe tổng quan của mèo bạn, bao gồm kiểm tra trọng lượng, kiểm tra lông, tai và mắt, và kiểm tra các vấn đề sức khỏe cơ bản khác.</p>\r\n");
      out.write("                                <div class=\"d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                    <a class=\"btn btn-light btn-light-outline-0 rounded-pill py-3 px-5 me-4\" href=\"#\">Bắt đầu</a>\r\n");
      out.write("                                    <a class=\"btn btn-primary btn-primary-outline-0 rounded-pill py-3 px-5\" href=\"#\">Đặt bây giờ</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"carousel-item\">\r\n");
      out.write("                        <img src=\"template/web/img/carousel-2.jpg\" class=\"img-fluid\" alt=\"Image\">\r\n");
      out.write("                        <div class=\"carousel-caption\">\r\n");
      out.write("                            <div class=\"p-3\" style=\"max-width: 900px;\">\r\n");
      out.write("                                <h4 class=\"text-primary text-uppercase mb-3\" style=\"letter-spacing: 3px;\">PET SHOP</h4>\r\n");
      out.write("                                <h1 class=\"display-1 text-capitalize text-dark mb-3\">Tiêm phòng cho thú cưng</h1>\r\n");
      out.write("                                <p class=\"mx-md-5 fs-4 px-5 mb-5 text-dark\">Chúng tôi cung cấp chương trình tiêm phòng đầy đủ và hiệu quả để bảo vệ mèo của bạn khỏi các bệnh nguy hiểm như tức huyết, viêm phổi và các bệnh truyền nhiễm khác.</p>\r\n");
      out.write("                                <div class=\"d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                    <a class=\"btn btn-light btn-light-outline-0 rounded-pill py-3 px-5 me-4\" href=\"#\">Bắt đầu</a>\r\n");
      out.write("                                    <a class=\"btn btn-primary btn-primary-outline-0 rounded-pill py-3 px-5\" href=\"#\">Đặt bây giờ</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"carousel-item\">\r\n");
      out.write("                        <img src=\"template/web/img/carousel-3.jpg\" class=\"img-fluid\" alt=\"Image\">\r\n");
      out.write("                        <div class=\"carousel-caption\">\r\n");
      out.write("                            <div class=\"p-3\" style=\"max-width: 900px;\">\r\n");
      out.write("                                <h4 class=\"text-primary text-uppercase mb-3\" style=\"letter-spacing: 3px;\">PET SHOP</h4>\r\n");
      out.write("                                <h1 class=\"display-1 text-capitalize text-dark\">Đặt đơn đi dạo</h1>\r\n");
      out.write("                                <p class=\"mx-md-5 fs-4 px-5 mb-5 text-dark\">Chúng tôi cung cấp dịch vụ đi dạo dành cho mèo để giúp thú cưng của bạn có thêm vận động, giảm căng thẳng và khám phá thế giới xung quanh một cách an toàn.</p>\r\n");
      out.write("                                <div class=\"d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                    <a class=\"btn btn-light btn-light-outline-0 rounded-pill py-3 px-5 me-4\" href=\"#\">Bắt đầu</a>\r\n");
      out.write("                                    <a class=\"btn btn-primary btn-primary-outline-0 rounded-pill py-3 px-5\" href=\"#\">Đặt bây giờ</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselId\" data-bs-slide=\"prev\">\r\n");
      out.write("                    <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                    <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("                </button>\r\n");
      out.write("                <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselId\" data-bs-slide=\"next\">\r\n");
      out.write("                    <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                    <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Carousel End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Services Start -->\r\n");
      out.write("        <div class=\"container-fluid services py-5\">\r\n");
      out.write("            <div class=\"container py-5\">\r\n");
      out.write("                <div class=\"mx-auto text-center mb-5\" style=\"max-width: 800px;\">\r\n");
      out.write("                    <p class=\"fs-4 text-uppercase text-center text-primary\">Dịch vụ của chúng tôi</p>\r\n");
      out.write("                    <h1 class=\"display-3\">Chăm sóc cùng PET SHOP</h1>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row g-4\">\r\n");
      out.write("                \t\r\n");
      out.write("\t                    <div class=\"col-lg-6\">\r\n");
      out.write("\t                        <div class=\"services-item bg-light border-4 border-end border-primary rounded p-4\">\r\n");
      out.write("\t                            <div class=\"row align-items-center\">\r\n");
      out.write("\t                                <div class=\"col-8\">\r\n");
      out.write("\t                                    <div class=\"services-content text-end\">\r\n");
      out.write("\t                                        <h3>Kiểm tra sức khỏe cơ bản</h3>\r\n");
      out.write("\t                                        <p>Đội ngũ bác sĩ thú y chuyên nghiệp của chúng tôi sẽ kiểm tra sức khỏe tổng quan của mèo bạn, bao gồm kiểm tra trọng lượng, kiểm tra lông, tai và mắt, và kiểm tra các vấn đề sức khỏe cơ bản khác.</p>\r\n");
      out.write("\t                                        <a href=\"#\" class=\"btn btn-primary btn-primary-outline-0 rounded-pill py-2 px-4\">Đặt hàng</a>\r\n");
      out.write("\t                                    </div>\r\n");
      out.write("\t                                </div>\r\n");
      out.write("\t                                <div class=\"col-4\">\r\n");
      out.write("\t                                    <div class=\"services-img d-flex align-items-center justify-content-center rounded\">\r\n");
      out.write("\t                                        <img src=\"template/web/img/dichvumeo1.jpg\" class=\"img-fluid rounded\" alt=\"\">\r\n");
      out.write("\t                                    </div>\r\n");
      out.write("\t                                </div>\r\n");
      out.write("\t                            </div>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <div class=\"services-item bg-light border-4 border-start border-primary rounded p-4\">\r\n");
      out.write("                            <div class=\"row align-items-center\">\r\n");
      out.write("                                <div class=\"col-4\">\r\n");
      out.write("                                    <div class=\"services-img d-flex align-items-center justify-content-center rounded\">\r\n");
      out.write("                                        <img src=\"template/web/img/dichvumeo2.jpg\" class=\"img-fluid rounded\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-8\">\r\n");
      out.write("                                    <div class=\"services-content text-start\">\r\n");
      out.write("                                        <h3>Tiêm phòng</h3>\r\n");
      out.write("                                        <p>Chúng tôi cung cấp chương trình tiêm phòng đầy đủ và hiệu quả để bảo vệ mèo của bạn khỏi các bệnh nguy hiểm như tức huyết, viêm phổi và các bệnh truyền nhiễm khác.</p>\r\n");
      out.write("                                        <a href=\"#\" class=\"btn btn-primary btn-primary-outline-0 rounded-pill py-2 px-4\">Đặt hàng</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <div class=\"services-item bg-light border-4 border-end border-primary rounded p-4\">\r\n");
      out.write("                            <div class=\"row align-items-center\">\r\n");
      out.write("                                <div class=\"col-8\">\r\n");
      out.write("                                    <div class=\"services-content text-end\">\r\n");
      out.write("                                        <h3>Đặt đơn đi dạo</h3>\r\n");
      out.write("                                        <p>Chúng tôi cung cấp dịch vụ đi dạo dành cho mèo để giúp thú cưng của bạn có thêm vận động, giảm căng thẳng và khám phá thế giới xung quanh một cách an toàn.</p>\r\n");
      out.write("                                        <a href=\"#\" class=\"btn btn-primary btn-primary-outline-0 rounded-pill py-2 px-4\">Đặt hàng</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-4\">\r\n");
      out.write("                                    <div class=\"services-img d-flex align-items-center justify-content-center rounded\">\r\n");
      out.write("                                        <img src=\"template/web/img/dichvumeo3.jpg\" class=\"img-fluid rounded\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <div class=\"services-item bg-light border-4 border-start border-primary rounded p-4\">\r\n");
      out.write("                            <div class=\"row align-items-center\">\r\n");
      out.write("                                <div class=\"col-4\">\r\n");
      out.write("                                    <div class=\"services-img d-flex align-items-center justify-content-center rounded\">\r\n");
      out.write("                                        <img src=\"template/web/img/DongVat.jpg\" class=\"img-fluid rounded\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-8\">\r\n");
      out.write("                                    <div class=\"services-content text-start\">\r\n");
      out.write("                                        <h3>Cung cấp các sản phẩm</h3>\r\n");
      out.write("                                        <p>Cát đậu nành , Cát gỗ, Yếm họa tiết cute cho boss, Sữa tắm SOS,Kem đánh răng nhỏ ,Sữa Bio -Milk 100g</p>\r\n");
      out.write("                                        <a href=\"#\" class=\"btn btn-primary btn-primary-outline-0 rounded-pill py-2 px-4\">Đặt hàng</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <div class=\"services-item bg-light border-4 border-end border-primary rounded p-4\">\r\n");
      out.write("                            <div class=\"row align-items-center\">\r\n");
      out.write("                                <div class=\"col-8\">\r\n");
      out.write("                                    <div class=\"services-content text-end\">\r\n");
      out.write("                                        <h3>Tắm rửa và làm đẹp</h3>\r\n");
      out.write("                                        <p>Chúng tôi cung cấp dịch vụ tắm rửa và làm đẹp chuyên nghiệp để giữ cho lông mèo của bạn luôn sạch sẽ và trông thật đẹp.</p>\r\n");
      out.write("                                        <a href=\"#\" class=\"btn btn-primary btn-primary-outline-0 rounded-pill py-2 px-4\">Đặt hàng</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-4\">\r\n");
      out.write("                                    <div class=\"services-img d-flex align-items-center justify-content-center rounded\">\r\n");
      out.write("                                        <img src=\"template/web/img/dichvumeo5.webp\" class=\"img-fluid rounded\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <div class=\"services-item bg-light border-4 border-start border-primary rounded p-4\">\r\n");
      out.write("                            <div class=\"row align-items-center\">\r\n");
      out.write("                                <div class=\"col-4\">\r\n");
      out.write("                                    <div class=\"services-img d-flex align-items-center justify-content-center rounded\">\r\n");
      out.write("                                        <img src=\"template/web/img/dichvumeo6.jpg\" class=\"img-fluid rounded\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-8\">\r\n");
      out.write("                                    <div class=\"services-content text-start\">\r\n");
      out.write("                                        <h3>Dịch vụ điều trị y tế</h3>\r\n");
      out.write("                                        <p>Bác sĩ thú y của chúng tôi có kinh nghiệm và tận tình trong việc cung cấp điều trị y tế và chăm sóc đặc biệt cho mèo khi chúng cần.</p>\r\n");
      out.write("                                        <a href=\"#\" class=\"btn btn-primary btn-primary-outline-0 rounded-pill py-2 px-4\">Đặt hàng</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <div class=\"services-item bg-light border-4 border-end border-primary rounded p-4\">\r\n");
      out.write("                            <div class=\"row align-items-center\">\r\n");
      out.write("                                <div class=\"col-8\">\r\n");
      out.write("                                    <div class=\"services-content text-end\">\r\n");
      out.write("                                        <h3>Dịch vụ nuôi dưỡng và dinh dưỡng</h3>\r\n");
      out.write("                                        <p>Chúng tôi cung cấp các sản phẩm thức ăn chất lượng cao và chế độ dinh dưỡng phù hợp để đảm bảo mèo của bạn luôn khỏe mạnh và tràn đầy năng lượng.</p>\r\n");
      out.write("                                        <a href=\"#\" class=\"btn btn-primary btn-primary-outline-0 rounded-pill py-2 px-4\">Đặt hàng</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-4\">\r\n");
      out.write("                                    <div class=\"services-img d-flex align-items-center justify-content-center rounded\">\r\n");
      out.write("                                        <img src=\"template/web/img/dichvumeo7.webp\" class=\"img-fluid rounded\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <div class=\"services-item bg-light border-4 border-start border-primary rounded p-4\">\r\n");
      out.write("                            <div class=\"row align-items-center\">\r\n");
      out.write("                                <div class=\"col-4\">\r\n");
      out.write("                                    <div class=\"services-img d-flex align-items-center justify-content-center rounded\">\r\n");
      out.write("                                        <img src=\"template/web/img/dichvumeo8.jpg\" class=\"img-fluid rounded\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-8\">\r\n");
      out.write("                                    <div class=\"services-content text-start\">\r\n");
      out.write("                                        <h3>Dịch vụ giáo dục và huấn luyện</h3>\r\n");
      out.write("                                        <p>Chúng tôi cung cấp các khóa học giáo dục và huấn luyện để giúp mèo của bạn phát triển hành vi tích cực và tăng cường mối quan hệ giữa bạn và thú cưng của mình.</p>\r\n");
      out.write("                                        <a href=\"#\" class=\"btn btn-primary btn-primary-outline-0 rounded-pill py-2 px-4\">Đặt hàng</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <div class=\"services-btn text-center\">\r\n");
      out.write("                            <a href=\"#\" class=\"btn btn-primary btn-primary-outline-0 rounded-pill py-3 px-5\">Service More</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Services End -->\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <!-- About Start -->\r\n");
      out.write("        <div class=\"container-fluid about py-5\">\r\n");
      out.write("            <div class=\"container py-5\">\r\n");
      out.write("                <div class=\"row g-5 align-items-center\">\r\n");
      out.write("                    <div class=\"col-lg-5\">\r\n");
      out.write("                        <div class=\"video\">\r\n");
      out.write("                            <img src=\"template/web/img/about-1.webp\" class=\"img-fluid rounded\" alt=\"\">\r\n");
      out.write("                            <div class=\"position-absolute rounded border-5 border-top border-start border-white\" style=\"bottom: 0; right: 0;;\">\r\n");
      out.write("                                <img src=\"template/web/img/about-1.webp\" class=\"img-fluid rounded\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-play\" data-bs-toggle=\"modal\" data-src=\"https://www.youtube.com/watch?v=_Qy0PR4gKEA\" data-bs-target=\"#videoModal\">\r\n");
      out.write("                                <span></span>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-7\">\r\n");
      out.write("                        <p class=\"fs-4 text-uppercase text-primary\">Về chúng tôi</p>\r\n");
      out.write("                        <h1 class=\"display-4 mb-4\">Trung Tâm Chăm Sóc Và Phụ Kiện Thú Cưng Tốt Nhất Cho Bạn</h1>\r\n");
      out.write("                        <p class=\"mb-4\">Chúng tôi là nơi nâng cao chất lượng cuộc sống của các thành viên bốn chân trong gia đình của bạn. Tại Trung Tâm Chăm Sóc Thú Cưng Tốt Nhất, chúng tôi cam kết cung cấp cho thú cưng của bạn sự quan tâm, chăm sóc và yêu thương tối đa</p>\r\n");
      out.write("                        <div class=\"row g-4\">\r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                    <i class=\"fab fa-gitkraken fa-3x text-primary\"></i>\r\n");
      out.write("                                    <div class=\"ms-4\">\r\n");
      out.write("                                        <h5 class=\"mb-2\">Chăm sóc sức khỏe</h5>\r\n");
      out.write("                                        <p class=\"mb-0\">Đội ngũ bác sĩ thú y chuyên nghiệp của chúng tôi sẽ đảm bảo rằng thú cưng của bạn luôn ở trạng thái sức khỏe tốt nhất. Từ kiểm tra định kỳ đến điều trị y tế, chúng tôi có mọi thứ để giữ cho thú cưng của bạn mạnh mẽ và hạnh phúc.</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6\">\r\n");
      out.write("                                <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                    <i class=\"fas fa-gift fa-3x text-primary\"></i>\r\n");
      out.write("                                    <div class=\"ms-4\">\r\n");
      out.write("                                        <h5 class=\"mb-2\">Dịch vụ chăm sóc</h5>\r\n");
      out.write("                                        <p class=\"mb-0\">Tại Trung Tâm Chăm Sóc Thú Cưng Tốt Nhất, chúng tôi cung cấp các dịch vụ chăm sóc chuyên sâu như tắm gội, cắt tỉa lông, và chăm sóc da dành riêng cho thú cưng của bạn. Chúng tôi cam kết mang lại cho thú cưng của bạn sự thoải mái và sảng khoái.</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"my-4\">Chúng tôi cung cấp các lớp đào tạo từ cơ bản đến nâng cao cho thú cưng của bạn, giúp chúng phát triển kỹ năng và tinh thần. Ngoài ra, chúng tôi cũng tổ chức các hoạt động thú vị như đi dạo, thi đấu và sinh nhật để tạo ra những kỷ niệm đáng nhớ cho bạn và thú cưng của mình.\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <p class=\"mb-4\">Hãy đến với chúng tôi và trải nghiệm sự chăm sóc tận tình và chuyên nghiệp từ đội ngũ của chúng tôi. Thú cưng của bạn xứng đáng nhận được những điều tốt nhất, và chúng tôi ở đây để mang lại điều đó cho họ.\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <a href=\"#\" class=\"btn btn-primary btn-primary-outline-0 rounded-pill py-3 px-5\">Explore More</a>\r\n");
      out.write("                    </div> \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Modal Video -->\r\n");
      out.write("        <div class=\"modal fade\" id=\"videoModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content rounded-0\">\r\n");
      out.write("                    <div class=\"modal-header\">\r\n");
      out.write("                        <h5 class=\"modal-title\" id=\"exampleModalLabel\">Youtube Video</h5>\r\n");
      out.write("                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-body\">\r\n");
      out.write("                        <!-- 16:9 aspect ratio -->\r\n");
      out.write("                        <div class=\"ratio ratio-16x9\">\r\n");
      out.write("                            <iframe class=\"embed-responsive-item\" src=\"\" id=\"video\" allowfullscreen allowscriptaccess=\"always\"\r\n");
      out.write("                                allow=\"autoplay\"></iframe>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- About End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Appointment Start -->\r\n");
      out.write("        <div class=\"container-fluid appointment py-5\">\r\n");
      out.write("            <div class=\"container py-5\">\r\n");
      out.write("                <div class=\"row g-5 align-items-center\">\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <div class=\"appointment-form p-5\" style=\"background: linear-gradient(rgba(255, 192, 203, 0.4), rgba(255, 192, 203, 0.4))\">\r\n");
      out.write("                            <p class=\"fs-4 text-uppercase text-primary\">Liên lạc</p>\r\n");
      out.write("                            <h1 class=\"display-4 mb-4 text-white\">Gửi thông tin để shop tư vấn</h1>\r\n");
      out.write("                            <form id =\"formSubmit\">\r\n");
      out.write("                                <div class=\"row gy-3 gx-4\">\r\n");
      out.write("                                    <div class=\"col-lg-6\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control py-3 border-white bg-transparent text-white\" name=\"sdtGiaoHang\" id=\"sdtGiaoHang\" placeholder=\"Nhập số điện thoại của bạn\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-lg-6\">\r\n");
      out.write("                                        <input type=\"email\" class=\"form-control py-3 border-white bg-transparent text-white \" name=\"diaChiGiaoHang\" id=\"diaChiGiaoHang\" placeholder=\"Nhập đỉa chỉ của bạn\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-lg-12\">\r\n");
      out.write("                                        <textarea class=\"form-control border-white bg-transparent text-white\" cols=\"30\" rows=\"5\" placeholder=\"Nhập những thông tin lưu í cho shop ở đây:\"></textarea>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-lg-12\">\r\n");
      out.write("                                        <button type=\"button\" id=\"datLichHen\" class=\"btn btn-primary btn-primary-outline-0 w-100 py-3 px-5\">Đặt lịch ngay</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-6\">\r\n");
      out.write("                        <div class=\"appointment-time p-5\">\r\n");
      out.write("                            <h1 class=\"display-5 mb-4b text-white\">Giờ mở cửa</h1>\r\n");
      out.write("                            <div class=\"d-flex justify-content-between fs-5 text-white\">\r\n");
      out.write("                                <p>Thứ bảy:</p>\r\n");
      out.write("                                <p>09:00 am – 10:00 pm</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"d-flex justify-content-between fs-5 text-white\">\r\n");
      out.write("                                <p>Chủ Nhật:</p>\r\n");
      out.write("                                <p>09:00 am – 10:00 pm</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"d-flex justify-content-between fs-5 text-white\">\r\n");
      out.write("                                <p>Thứ hai:</p>\r\n");
      out.write("                                <p>09:00 am – 10:00 pm</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"d-flex justify-content-between fs-5 text-white\">\r\n");
      out.write("                                <p>Thứ ba:</p>\r\n");
      out.write("                                <p>09:00 am – 10:00 pm</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"d-flex justify-content-between fs-5 text-white\">\r\n");
      out.write("                                <p>Thứ tư:</p>\r\n");
      out.write("                                <p>09:00 am – 08:00 pm</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"d-flex justify-content-between fs-5 text-white mb-4\">\r\n");
      out.write("                                <p>Thứ năm:</p>\r\n");
      out.write("                                <p>09:00 am – 05:00 pm</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"d-flex justify-content-between fs-5 text-white mb-4\">\r\n");
      out.write("                                <p>Thứ sáu:</p>\r\n");
      out.write("                                <p>ĐÓNG CỬA</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p class=\"text-white\">Theo dõi các ưu đã theo đợt để được cung cấp tốt nhất.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Counter Start -->\r\n");
      out.write("            <div class=\"container-fluid counter-section\">\r\n");
      out.write("                <div class=\"container py-5\">\r\n");
      out.write("                    <div class=\"row g-5 justify-content-center\">\r\n");
      out.write("                        <div class=\"col-md-6 col-lg-4 col-xl-4\">\r\n");
      out.write("                            <div class=\"counter-item p-5\">\r\n");
      out.write("                                <div class=\"counter-content bg-white p-4\">\r\n");
      out.write("                                    <i class=\"fas fa-globe fa-5x text-primary mb-3\"></i>\r\n");
      out.write("                                    <h5 class=\"text-primary\">Khách hàng toàn cầu</h5>\r\n");
      out.write("                                    <div class=\"svg-img\">\r\n");
      out.write("                                        <svg width=\"100\" height=\"50\">\r\n");
      out.write("                                            <polygon points=\"55, 10 85, 55 25, 55 25,\" style=\"fill: #DCCAF2;\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"counter-quantity\">\r\n");
      out.write("                                    <span class=\"text-white fs-2 fw-bold\" data-toggle=\"counter-up\">379</span>\r\n");
      out.write("                                    <span class=\"h1 fw-bold text-white\">+</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6 col-lg-4 col-xl-4\">\r\n");
      out.write("                            <div class=\"counter-item p-5\">\r\n");
      out.write("                                <div class=\"counter-content bg-white p-4\">\r\n");
      out.write("                                    <i class=\"fas fa-spa fa-5x text-primary mb-3\"></i>\r\n");
      out.write("                                    <h5 class=\"text-primary\">Dịch vụ</h5>\r\n");
      out.write("                                    <div class=\"svg-img\">\r\n");
      out.write("                                        <svg width=\"100\" height=\"50\">\r\n");
      out.write("                                            <polygon points=\"55, 10 85, 55 25, 55 25,\" style=\"fill: #DCCAF2;\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"counter-quantity\">\r\n");
      out.write("                                    <span class=\"text-white fs-2 fw-bold\" data-toggle=\"counter-up\">829</span>\r\n");
      out.write("                                    <span class=\"h1 fw-bold text-white\">+</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-6 col-lg-4 col-xl-4\">\r\n");
      out.write("                            <div class=\"counter-item p-5\">\r\n");
      out.write("                                <div class=\"counter-content bg-white p-4\">\r\n");
      out.write("                                    <i class=\"fas fa-users fa-5x text-primary mb-3\"></i>\r\n");
      out.write("                                    <h5 class=\"text-primary\">Khách VIP</h5>\r\n");
      out.write("                                    <div class=\"svg-img\">\r\n");
      out.write("                                        <svg width=\"100\" height=\"50\">\r\n");
      out.write("                                            <polygon points=\"55, 10 85, 55 25, 55 25,\" style=\"fill: #DCCAF2;\"/>\r\n");
      out.write("                                        </svg>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"counter-quantity\">\r\n");
      out.write("                                    <span class=\"text-white fs-2 fw-bold\" data-toggle=\"counter-up\">713</span>\r\n");
      out.write("                                    <span class=\"h1 fw-bold text-white\">+</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Counter End -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Appointment End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Pricing Start -->\r\n");
      out.write("        <div class=\"container-fluid pricing py-5\" style=\"background: var(--bs-primary);\" >\r\n");
      out.write("            <div class=\"container py-5\">\r\n");
      out.write("                <div class=\"owl-carousel pricing-carousel\">\r\n");
      out.write("                    <div class=\"pricing-item\">\r\n");
      out.write("                        <div class=\"rounded pricing-content\">\r\n");
      out.write("                            <div class=\"d-flex align-items-center justify-content-between bg-light rounded-top border-3 border-bottom border-primary p-4\">\r\n");
      out.write("                                <h1 class=\"display-4 mb-0\">\r\n");
      out.write("                                    <small class=\"align-top text-muted\" style=\"font-size: 22px; line-height: 45px;\">$</small>49<small class=\"text-muted\" style=\"font-size: 16px; line-height: 40px;\">/Mo</small>\r\n");
      out.write("                                </h1>\r\n");
      out.write("                                <h5 class=\"text-primary text-uppercase m-0\">Gói Cơ bản</h5>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"p-4\">\r\n");
      out.write("                                <p><i class=\"fa fa-check text-primary me-2\"></i>Massage cơ bản</p>\r\n");
      out.write("                                <p><i class=\"fa fa-check text-primary me-2\"></i>Cắt tỉa lông cơ bản</p>\r\n");
      out.write("                                <p><i class=\"fa fa-check text-primary me-2\"></i>Tắm gội toàn thân</p>\r\n");
      out.write("                                <p><i class=\"fa fa-check text-primary me-2\"></i>Khám sức khoẻ cơ bản</p>\r\n");
      out.write("                                <p><i class=\"fa fa-check text-primary me-2\"></i>Vệ sinh thân thể</p>\r\n");
      out.write("                                <a href=\"\" class=\"btn btn-primary btn-primary-outline-0 rounded-pill my-2 px-4\">Order Now</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"pricing-item\">\r\n");
      out.write("                        <div class=\"pricing-content rounded\">\r\n");
      out.write("                            <div class=\"d-flex align-items-center justify-content-between bg-light rounded-top border-3 border-bottom border-primary p-4\">\r\n");
      out.write("                                <h1 class=\"display-4 mb-0\">\r\n");
      out.write("                                    <small class=\"align-top text-muted\" style=\"font-size: 22px; line-height: 45px;\">$</small>99<small class=\"text-muted\" style=\"font-size: 16px; line-height: 40px;\">/Mo</small>\r\n");
      out.write("                                </h1>\r\n");
      out.write("                                <h5 class=\"text-primary text-uppercase m-0\">Gói Gia đình</h5>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"p-4\">\r\n");
      out.write("                                <p><i class=\"fa fa-check text-primary me-2\"></i>Massage cơ bản</p>\r\n");
      out.write("                                <p><i class=\"fa fa-check text-primary me-2\"></i>Cắt tỉa lông cơ bản</p>\r\n");
      out.write("                                <p><i class=\"fa fa-check text-primary me-2\"></i>Tắm gội toàn thân</p>\r\n");
      out.write("                                <p><i class=\"fa fa-check text-primary me-2\"></i>Khám sức khoẻ cơ bản</p>\r\n");
      out.write("                                <p><i class=\"fa fa-check text-primary me-2\"></i>Vệ sinh thân thể</p>\r\n");
      out.write("                                <a href=\"\" class=\"btn btn-primary btn-primary-outline-0 rounded-pill my-2 px-4\">Order Now</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"pricing-item\">\r\n");
      out.write("                        <div class=\"pricing-content rounded\">\r\n");
      out.write("                            <div class=\"d-flex align-items-center justify-content-between bg-light rounded-top border-3 border-bottom border-primary p-4\">\r\n");
      out.write("                                <h1 class=\"display-4 mb-0\">\r\n");
      out.write("                                    <small class=\"align-top text-muted\" style=\"font-size: 22px; line-height: 45px;\">$</small>149<small class=\"text-muted\" style=\"font-size: 16px; line-height: 40px;\">/Mo</small>\r\n");
      out.write("                                </h1>\r\n");
      out.write("                                <h5 class=\"text-primary text-uppercase m-0\">Gói VIP</h5>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"p-4\">\r\n");
      out.write("                                <p><i class=\"fa fa-check text-primary me-2\"></i>Massage toàn thân</p>\r\n");
      out.write("                                <p><i class=\"fa fa-check text-primary me-2\"></i>Cắt tỉa lông toàn thân</p>\r\n");
      out.write("                                <p><i class=\"fa fa-check text-primary me-2\"></i>Tắm gội và sấy khô</p>\r\n");
      out.write("                                <p><i class=\"fa fa-check text-primary me-2\"></i>Khám sức khoẻ toàn thân</p>\r\n");
      out.write("                                <p><i class=\"fa fa-check text-primary me-2\"></i>Vệ sinh thân thể</p>\r\n");
      out.write("                                <a href=\"\" class=\"btn btn-primary btn-primary-outline-0 rounded-pill my-2 px-4\">Order Now</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"pricing-item\">\r\n");
      out.write("                        <div class=\"pricing-content rounded\">\r\n");
      out.write("                            <div class=\"d-flex align-items-center justify-content-between bg-light rounded-top border-3 border-bottom border-primary p-4\">\r\n");
      out.write("                                <h1 class=\"display-4 mb-0\">\r\n");
      out.write("                                    <small class=\"align-top text-muted\" style=\"font-size: 22px; line-height: 45px;\">$</small>199<small class=\"text-muted\" style=\"font-size: 16px; line-height: 40px;\">/Mo</small>\r\n");
      out.write("                                </h1>\r\n");
      out.write("                                <h5 class=\"text-primary text-uppercase m-0\">Gói tốt nhất</h5>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"p-4\">\r\n");
      out.write("                                <p><i class=\"fa fa-check text-primary me-2\"></i>Massage toàn thân</p>\r\n");
      out.write("                                <p><i class=\"fa fa-check text-primary me-2\"></i>Cắt tỉa,nhộm màu lông</p>\r\n");
      out.write("                                <p><i class=\"fa fa-check text-primary me-2\"></i>Tắm gội và sấy khô</p>\r\n");
      out.write("                                <p><i class=\"fa fa-check text-primary me-2\"></i>Khám sức khoẻ toàn thân</p>\r\n");
      out.write("                                <p><i class=\"fa fa-check text-primary me-2\"></i>Dịch vụ điều trị y tế </p>\r\n");
      out.write("                                <a href=\"\" class=\"btn btn-primary btn-primary-outline-0 rounded-pill my-2 px-4\">Order Now</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Pricing End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Team Start -->\r\n");
      out.write("        <div class=\"container-fluid team py-5\">\r\n");
      out.write("            <div class=\"container py-5\">\r\n");
      out.write("                <div class=\"text-center mx-auto mb-5\" style=\"max-width: 800px;\">\r\n");
      out.write("                    <p class=\"fs-4 text-uppercase text-primary\">PET SHOP</p>\r\n");
      out.write("                    <h1 class=\"display-4 mb-4\">Đội ngũ của chúng tôi</h1>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row g-4\">\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                        <div class=\"team-item\">\r\n");
      out.write("                            <div class=\"team-img rounded-top\">\r\n");
      out.write("                                <img src=\"template/web/img/bacsy_1.jpg\" class=\"img-fluid w-100 rounded-top bg-light\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"team-text rounded-bottom text-center p-4\">\r\n");
      out.write("                                <h3 class=\"text-white\">Oliva Mia</h3>\r\n");
      out.write("                                <p class=\"mb-0 text-white\">Chuyên gia bác sỹ</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"team-social\">\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle\" href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                        <div class=\"team-item\">\r\n");
      out.write("                            <div class=\"team-img rounded-top\">\r\n");
      out.write("                                <img src=\"template/web/img/bacsy_6.jpg\" class=\"img-fluid w-100 rounded-top bg-light\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"team-text rounded-bottom text-center p-4\">\r\n");
      out.write("                                <h3 class=\"text-white\">Charlotte Ross</h3>\r\n");
      out.write("                                <p class=\"mb-0 text-white\">Chuyên gia bác sỹ</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"team-social\">\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle\" href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                        <div class=\"team-item\">\r\n");
      out.write("                            <div class=\"team-img rounded-top\">\r\n");
      out.write("                                <img src=\"template/web/img/bacsy_7.jpg\" class=\"img-fluid w-100 rounded-top bg-light\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"team-text rounded-bottom text-center p-4\">\r\n");
      out.write("                                <h3 class=\"text-white\">Amelia Luna</h3>\r\n");
      out.write("                                <p class=\"mb-0 text-white\">Chuyên gia bác sỹ</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"team-social\">\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle\" href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                        <div class=\"team-item\">\r\n");
      out.write("                            <div class=\"team-img rounded-top\">\r\n");
      out.write("                                <img src=\"template/web/img/bacsy_9.jpg\" class=\"img-fluid w-100 rounded-top bg-light\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"team-text rounded-bottom text-center p-4\">\r\n");
      out.write("                                <h3 class=\"text-white\">Isabella Evelyn</h3>\r\n");
      out.write("                                <p class=\"mb-0 text-white\">Chuyên gia bác sỹ</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"team-social\">\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle\" href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Team End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Testimonial Start -->\r\n");
      out.write("        <div class=\"container-fluid testimonial py-5\">\r\n");
      out.write("            <div class=\"container py-5\">\r\n");
      out.write("                <div class=\"text-center mx-auto mb-5\" style=\"max-width: 800px;\">\r\n");
      out.write("                    <p class=\"fs-4 text-uppercase text-primary\">REVIEW</p>\r\n");
      out.write("                    <h1 class=\"display-4 mb-4 text-white\">Khách hàng của chúng tôi nói gì !</h1>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"owl-carousel testimonial-carousel\">\r\n");
      out.write("                    <div class=\"testimonial-item rounded p-4\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-4\">\r\n");
      out.write("                                <div class=\"d-flex flex-column mx-auto\">\r\n");
      out.write("                                    <div class=\"rounded-circle mb-4\" style=\"border: dashed; border-color: var(--bs-white);\">\r\n");
      out.write("                                        <img src=\"template/web/img/testimonial-1.jpg\" class=\"img-fluid rounded-circle\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"text-center\">\r\n");
      out.write("                                        <h4 class=\"mb-2 text-primary\">Lưu Ngọc Yến Như</h4>\r\n");
      out.write("                                        <p class=\"m-0 text-white\">Sinh viên</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-8\">\r\n");
      out.write("                                <div class=\"position-absolute\" style=\"top: 20px; right: 25px;\">\r\n");
      out.write("                                    <i class=\"fa fa-quote-right fa-2x text-secondary\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"testimonial-content\">\r\n");
      out.write("                                    <div class=\"d-flex mb-4\">\r\n");
      out.write("                                        <i class=\"fas fa-star text-primary\"></i>\r\n");
      out.write("                                        <i class=\"fas fa-star text-primary\"></i>\r\n");
      out.write("                                        <i class=\"fas fa-star text-primary\"></i>\r\n");
      out.write("                                        <i class=\"fas fa-star text-primary\"></i>\r\n");
      out.write("                                        <i class=\"fas fa-star\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p class=\"fs-5 mb-0 text-white\">\r\n");
      out.write("                                        Shop cung cấp các dịch vụ cho mèo với giá cả phải chăng, chị chủ với anh chủ tư vấn rất là nhiệt tình, vừa túi tiền sinh viên nên rất là an tâm giao mèo cho Shop.\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"testimonial-item rounded p-4\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-4\">\r\n");
      out.write("                                <div class=\"d-flex flex-column mx-auto\">\r\n");
      out.write("                                    <div class=\"rounded-circle mb-4\" style=\"border: dashed; border-color: var(--bs-white);\">\r\n");
      out.write("                                        <img src=\"template/web/img/testimonial-2.jpg\" class=\"img-fluid rounded-circle\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"text-center\">\r\n");
      out.write("                                        <h4 class=\"mb-2 text-primary\">Nguyễn Văn Linh</h4>\r\n");
      out.write("                                        <p class=\"m-0 text-white\">Kỹ sư</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-8\">\r\n");
      out.write("                                <div class=\"position-absolute\" style=\"top: 20px; right: 25px;\">\r\n");
      out.write("                                    <i class=\"fa fa-quote-right fa-2x text-secondary\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"testimonial-content\">\r\n");
      out.write("                                    <div class=\"d-flex mb-4\">\r\n");
      out.write("                                        <i class=\"fas fa-star text-primary\"></i>\r\n");
      out.write("                                        <i class=\"fas fa-star text-primary\"></i>\r\n");
      out.write("                                        <i class=\"fas fa-star text-primary\"></i>\r\n");
      out.write("                                        <i class=\"fas fa-star text-primary\"></i>\r\n");
      out.write("                                        <i class=\"fas fa-star\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p class=\"fs-5 mb-0 text-white\">Vừa đổ cát ra là bé mèo nhà bay dô cào cào đủ kiểu thích lắm. Shop gói hàng quá kĩ luôn, tới bao cát cũng gói chống sốc. Thùng đựng cát to, nói chung ưng hết sức. Cát mùi dễ chịu.</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"testimonial-item rounded p-4\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-4\">\r\n");
      out.write("                                <div class=\"d-flex flex-column mx-auto\">\r\n");
      out.write("                                    <div class=\"rounded-circle mb-4\" style=\"border: dashed; border-color: var(--bs-white);\">\r\n");
      out.write("                                        <img src=\"template/web/img/testimonial-3.jpg\" class=\"img-fluid rounded-circle\" alt=\"\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"text-center\">\r\n");
      out.write("                                        <h4 class=\"mb-2 text-primary\">Lê Hòa</h4>\r\n");
      out.write("                                        <p class=\"m-0 text-white\">Giáo viên</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-8\">\r\n");
      out.write("                                <div class=\"position-absolute\" style=\"top: 20px; right: 25px;\">\r\n");
      out.write("                                    <i class=\"fa fa-quote-right fa-2x text-secondary\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"testimonial-content\">\r\n");
      out.write("                                    <div class=\"d-flex mb-4\">\r\n");
      out.write("                                        <i class=\"fas fa-star text-primary\"></i>\r\n");
      out.write("                                        <i class=\"fas fa-star text-primary\"></i>\r\n");
      out.write("                                        <i class=\"fas fa-star text-primary\"></i>\r\n");
      out.write("                                        <i class=\"fas fa-star text-primary\"></i>\r\n");
      out.write("                                        <i class=\"fas fa-star\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p class=\"fs-5 mb-0 text-white\">Vì tính chất công việc nên phải vắng nhà vài tuần, thì PET SHOP là nơi mình luôn tin tưởng nhất để đặt những dịch vụ như trông nhờ mèo. Bé nhà mình lúc nào giữ hộ cũng rất năng động và sức khỏe không vấn đề gì, rất uy tín.\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Testimonial End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Contact Start -->\r\n");
      out.write("        <div class=\"container-fluid py-5\">\r\n");
      out.write("            <div class=\"container py-5\">\r\n");
      out.write("                <div class=\"row g-4 align-items-center\">\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <div class=\"row g-4\">\r\n");
      out.write("                            <div class=\"col-lg-4\">\r\n");
      out.write("                                <div class=\"d-inline-flex bg-light w-100 border border-primary p-4 rounded\">\r\n");
      out.write("                                    <i class=\"fas fa-map-marker-alt fa-2x text-primary me-4\"></i>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <h4>Address</h4>\r\n");
      out.write("                                        <p class=\"mb-0\">TRƯỜNG ĐẠI HỌC SƯ PHẠM KỸ THUẬT</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-lg-4\">\r\n");
      out.write("                                <div class=\"d-inline-flex bg-light w-100 border border-primary p-4 rounded\">\r\n");
      out.write("                                    <i class=\"fas fa-envelope fa-2x text-primary me-4\"></i>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <h4>Mail Us</h4>\r\n");
      out.write("                                        <p class=\"mb-0\">ute@udn.vn</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-lg-4\">\r\n");
      out.write("                                <div class=\"d-inline-flex bg-light w-100 border border-primary p-4 rounded\">\r\n");
      out.write("                                    <i class=\"fa fa-phone-alt fa-2x text-primary me-4\"></i>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <h4>Telephone</h4>\r\n");
      out.write("                                        <p class=\"mb-0\">(+012) 3456 7890 123</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <div class=\"rounded\">\r\n");
      out.write("                            <iframe class=\"rounded-top w-100\" \r\n");
      out.write("                            style=\"height: 450px; margin-bottom: -6px;\" src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d387191.33750346623!2d-73.97968099999999!3d40.6974881!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c24fa5d33f083b%3A0xc80b8f06e177fe62!2sNew%20York%2C%20NY%2C%20USA!5e0!3m2!1sen!2sbd!4v1694259649153!5m2!1sen!2sbd\" \r\n");
      out.write("                            loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\" text-center p-4 rounded-bottom bg-primary\">\r\n");
      out.write("                            <h4 class=\"text-white fw-bold\">Follow Us</h4>\r\n");
      out.write("                            <div class=\"d-flex align-items-center justify-content-center\">\r\n");
      out.write("                                <a href=\"#\" class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle me-3\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                                <a href=\"#\" class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle me-3\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                                <a href=\"#\" class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle me-3\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                                <a href=\"#\" class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                            </div>   \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Contact End -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$('#datLichHen').click(function (e) {\r\n");
      out.write("\t    e.preventDefault();\r\n");
      out.write("\t    var data = {};\r\n");
      out.write("\t    var formData = $('#formSubmit').serializeArray();\r\n");
      out.write("\t    $.each(formData, function (i, v) {\r\n");
      out.write("\t        data[\"\"+v.name+\"\"] = v.value;\r\n");
      out.write("\t        console.log(v.name+\" \"+v.value)\r\n");
      out.write("\t    });\r\n");
      out.write("\t    \tdatLich(data)\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\t\t function datLich(data) {\r\n");
      out.write("\t        $.ajax({\r\n");
      out.write("\t            url: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${APIurl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("\t            type: 'POST',\r\n");
      out.write("\t            contentType: 'application/json',\r\n");
      out.write("\t            data: JSON.stringify(data),\r\n");
      out.write("\t            success: function (result) {\r\n");
      out.write("\t            \twindow.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CartURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("?message=dhtv_success\";\r\n");
      out.write("\t            },\r\n");
      out.write("\t            error: function (error) {\r\n");
      out.write("\t            \twindow.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CartURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("?message=dhtv_lose\";\r\n");
      out.write("\t            }\r\n");
      out.write("\t        });\r\n");
      out.write("\t\t }\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /views/web/home.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("APIurl");
      // /views/web/home.jsp(5,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/api-datLich");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /views/web/home.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setVar("CartURL");
      // /views/web/home.jsp(6,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/web-cart");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }
}
