/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2024-05-08 16:05:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.web.team;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class team_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/OneDrive%20-%20University%20of%20Technology%20and%20Education/petshop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/petshop-cats/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1714401051284L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1710262135216L));
    _jspx_dependants.put("jar:file:/D:/OneDrive%20-%20University%20of%20Technology%20and%20Education/petshop/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/petshop-cats/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1710436164282L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>PETSHOP</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container-fluid team py-5\">\r\n");
      out.write("            <div class=\"container py-5\">\r\n");
      out.write("                <div class=\"text-center mx-auto mb-5\" style=\"max-width: 800px;\">\r\n");
      out.write("                    <p class=\"fs-4 text-uppercase text-primary\">Chuyên gia bác sỹ</p>\r\n");
      out.write("                    <h1 class=\"display-4 mb-4\">Đội ngũ bác sỹ </h1>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row g-4\">\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                        <div class=\"team-item\">\r\n");
      out.write("                            <div class=\"team-img rounded-top\">\r\n");
      out.write("                                <img src=\"template/web/img/bacsy_1.jpg\" class=\"img-fluid w-100 rounded-top bg-light\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"team-text rounded-bottom text-center p-4\">\r\n");
      out.write("                                <h3 class=\"text-white\">Oliva Mia</h3>\r\n");
      out.write("                                <p class=\"mb-0 text-white\">Chuyên gia bác sỹ</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"team-social\">\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle\" href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                        <div class=\"team-item\">\r\n");
      out.write("                            <div class=\"team-img rounded-top\">\r\n");
      out.write("                                <img src=\"template/web/img/bacsy_6.jpg\" class=\"img-fluid w-100 rounded-top bg-light\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"team-text rounded-bottom text-center p-4\">\r\n");
      out.write("                                <h3 class=\"text-white\">Charlotte Ross</h3>\r\n");
      out.write("                                <p class=\"mb-0 text-white\">Chuyên gia bác sỹ</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"team-social\">\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle\" href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                        <div class=\"team-item\">\r\n");
      out.write("                            <div class=\"team-img rounded-top\">\r\n");
      out.write("                                <img src=\"template/web/img/bacsy_7.jpg\" class=\"img-fluid w-100 rounded-top bg-light\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"team-text rounded-bottom text-center p-4\">\r\n");
      out.write("                                <h3 class=\"text-white\">Amelia Luna</h3>\r\n");
      out.write("                                <p class=\"mb-0 text-white\">Chuyên gia bác sỹ</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"team-social\">\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle\" href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-6 col-xl-3\">\r\n");
      out.write("                        <div class=\"team-item\">\r\n");
      out.write("                            <div class=\"team-img rounded-top\">\r\n");
      out.write("                                <img src=\"template/web/img/bacsy_9.jpg\" class=\"img-fluid w-100 rounded-top bg-light\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"team-text rounded-bottom text-center p-4\">\r\n");
      out.write("                                <h3 class=\"text-white\">Isabella Evelyn</h3>\r\n");
      out.write("                                <p class=\"mb-0 text-white\">Chuyên gia bác sỹ</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"team-social\">\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle mb-2\" href=\"#\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                                <a class=\"btn btn-light btn-light-outline-0 btn-square rounded-circle\" href=\"#\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
